name = "karrotmini-playground-bundle-storage"
workers_dev = true
compatibility_date = "2022-07-18"
compatibility_flags = [
  "url_standard"
]
account_id = "aad5c82543cd1f267b89737d0f56405e"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[[kv_namespaces]]
binding = "KV_BUNDLE_STORAGE"
id = "9ef081f0198246058c3c8a4f5d86a68d"
preview_id = "e35c547eef174fa1a224d799b64ffc62"

[build]
command = "worker-build --release"

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

[miniflare]
kv_persist = true
