name = "karrotmini-playground-management-api"
workers_dev = true
compatibility_date = "2022-05-22"
compatibility_flags = [
  "url_standard",
]
account_id = "aad5c82543cd1f267b89737d0f56405e"

# main = "./dist/worker.mjs"

[build]
watch_dir = "src/in"
command = "yarn esbuild src/worker.ts --bundle --outfile=dist/worker.mjs --format=esm"

# Deprecated in Wrangler v2, But still required for miniflare
[build.upload]
format = "modules"
dir = "./dist"
main = "./worker.mjs"

[[vars]]
HOSTNAME_PATTERN = "*.karrotmini.app"

[[services]]
binding = "playground"
service = "karrotmini-playground-adapter"

[miniflare.mounts]
playground-cloudflare-adapter = "../../playground-cloudflare-adapter/worker"
