name = "karrotmini-playground-adapter"
workers_dev = true
compatibility_date = "2022-05-22"
compatibility_flags = [
  "url_standard",
]
account_id = "aad5c82543cd1f267b89737d0f56405e"

[build]
watch_dir = "src"
command = "yarn esbuild src/worker.ts --bundle --minify --outfile=dist/worker.mjs --format=esm"

# Deprecated in Wrangler v2, But still required for miniflare
[build.upload]
format = "modules"
dir = "./dist"
main = "./worker.mjs"

[[kv_namespaces]]
binding = "KV_EVENT_STORE"
id = "853c2294e23848e5bc8128abca316c0e"
preview_id = "36e7d6e06600400e8c030e9c9a376980"

[[durable_objects.bindings]]
name = "DO_App"
class_name = "AppDurableObject"

[[durable_objects.bindings]]
name = "DO_BundleUpload"
class_name = "BundleUploadDurableObject"

[[durable_objects.bindings]]
name = "DO_CustomHost"
class_name = "CustomHostDurableObject"

[[durable_objects.bindings]]
name = "DO_UserProfile"
class_name = "UserProfileDurableObject"

[[migrations]]
tag = "v1"
new_classes = [
  "AppDurableObject",
  "BundleUploadDurableObject",
  "CustomHostDurableObject",
  "UserProfileDurableObject",
]

[miniflare]
kv_persist = true
durable_objects_persist = true
