name = "karrotmini-playground-adapter"
workers_dev = true
compatibility_date = "2022-05-22"
compatibility_flags = [
  "url_standard",
]
account_id = "aad5c82543cd1f267b89737d0f56405e"

main = "./dist/worker.mjs"

[[kv_namespaces]]
binding = "KV_EVENT_STORE"
id = ""
preview_id = ""

[[durable_objects.bindings]]
name = "DO_APP_REPOSITORY"
class_name = "AppRepositoryObject"

[[durable_objects.bindings]]
name = "DO_USER_PROFILE_REPOSITORY"
class_name = "UserProfileRepositoryObject"

[build]
watch_dir = "src/in"
command = "yarn esbuild src/worker.ts --bundle --outfile=dist/worker.mjs --format=esm"

# Deprecated in Wrangler v2, But still required for miniflare
[build.upload]
format = "modules"
dir = "./dist"
main = "./worker.mjs"
